import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/context/ThemeContext";
import Navbar from "@/components/Navbar";
import { ReduxProvider } from "./providers";

export const metadata: Metadata = {
  title: "POS System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100 dark:bg-gray-900 text-gray-800 dark:text-gray-100"
      >
        <ReduxProvider>
            <ThemeProvider>
                <Navbar/>
                <div>
                    {children}
                </div>
            </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
